### ISSUE TITLE
Ability to zoom in on images from (mobile - iOS)

### ISSUE THREAD

**Issue by misterdna** [tokenly/tokenly-cms#100]
I found that the photos embedded in articles (well, John Light's recent article, at least) aren't full screen and I can't zoom in on them in my iOS Safari browser. Not sure why some sites do this and some don't, but it's definitely nice to be able to zoom in on photos to see detail better, and not nice when the pics don't even go edge to edge in either orientation.

**Comment by cryptonaut420** [comment]
This should work on the new theme with the fix here: 6001d092792d5b8ebfff211d6ac2f7d8859b4243

**Comment by misterdna** [comment]
Nice, it's perfect now.
