### ISSUE TITLE
Make selecting a front page post easier on mobile (iOS at least)

### ISSUE THREAD

**Issue by misterdna** [tokenly/tokenly-cms#103]
I kept getting really flaky response when I touched the image for a front page post using my iPhone. I finally figured you you have to touch it twice, the first time seems to select the "box" for the post, and the second post actually gets you moving to that page. It's very unintuitive, I really thought for a time the image wasn't an active link. Can you remove the initial "selection" step that appears to occur when I touch an image for a post?

**Comment by cryptonaut420** [comment]
I was unable to reproduce this on my android (don't have an iOS device), but doing a bit of research and seems to be an iOS specific issue. I've attempted a fix, let me know if it still happens

**Comment by misterdna** [comment]
Yep, it works now with a single click! There's a bit of a weird delayed highlighting of the box after clicking, before the next page loads, but it's not worth messing with.

**Comment by cryptonaut420** [comment]
sweet :)
