### ISSUE TITLE
login link in page header not clickable at some resolutions

### ISSUE THREAD

**Issue by mdw** [tokenly/tokenly-cms#110]
__CSS issue in header  which puts the account link on second row menu beneath ad banner and it's not clickable. This happens for iPad Mini @ 768px, and generally at screen widths from 750px to 795px, and then again between 1050px and 1150px__

The link is still there, but somehow browsers don't apply to the FA icon or the link text. Tested in FF, Chrome, Safari and Opera on OSX. Yes Opera, don't laugh. Too lazy to test in Windows or Linux.

![ltb-homepage-screenshot-768x1024-ff](https://cloud.githubusercontent.com/assets/28559/11301238/7eb45a7a-8f63-11e5-9cf0-fc36f46b07ae.png)
![ltb-homepage-screenshot-1050px-chrome](https://cloud.githubusercontent.com/assets/28559/11301227/6452b3e8-8f63-11e5-9083-1b480aa69d1d.png)
![ltb-homepage-screenshot-768x1024-opera](https://cloud.githubusercontent.com/assets/28559/11301228/68f75962-8f63-11e5-84f1-c13a893c3e49.png)
![ltb-homepage-screenshot-1120px-safari](https://cloud.githubusercontent.com/assets/28559/11301231/6cf48652-8f63-11e5-8862-9b25f18366cd.png)

**Comment by cryptonaut420** [comment]
this should be fixed now, let me know if issue is still occuring

**Comment by mdw** [comment]
Quickly fixed for both resolution ranges, great work Nick!
