### ISSUE TITLE
Make it easier to find Blog posts by a user

### ISSUE THREAD

**Issue by pinheadmz** [tokenly/tokenly-cms#111]
I would love it if there was a single link I could share that would display all of the blog posts I contributed to on LTB. It's like a little resume of my contribution to the community, and it helps when I'm setting up a new interview with a guest or even on Reddit to show off a little expertise, etc.

Currently, it's like
1) Go to https://letstalkbitcoin.com/profile/user/pinheadmz
2) Scroll down to forum activity
3) Click on blog posts

But I would love it if that frame with the list of blog posts could be its own page, like

https://letstalkbitcoin.com/profile/user/pinheadmz/blogposts or something...?

What do you think?

**Comment by cryptonaut420** [comment]
Sounds good to me, check it out https://letstalkbitcoin.com/profile/user/pinheadmz/blog-posts and https://letstalkbitcoin.com/profile/user/pinheadmz/forum-posts

Clicking on the green "Forum Posts" or "Blog Posts" on your main profile will take you to those links as well

**Comment by pinheadmz** [comment]
Awesome thanks!
So fast :-0
