### ISSUE TITLE
Notifications don't dismiss once clicked

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#113]
![image](https://cloud.githubusercontent.com/assets/6858319/15676436/087c6ee4-26fb-11e6-85e4-f767c1f42ce0.png)

I've clicked several times to look at them, clicked some links, reloaded page, etc.  Seems like it's not recognizing that i've looked it and clearing the list for some reason.

**Comment by cryptonaut420** [comment]
fixed in tokentalk theme  7150c9a
