### ISSUE TITLE
Create basic documentation for how to add multiple and combinations of tokens

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#114]
I remember you explained this to me once in the LTB chat, but it seems to have been lost to time - Can you just give me a basic legend of how to do either separate or token combinations which I can then use to write more detailed step by step documentation for users?

**Comment by cryptonaut420** [comment]
For the list of tokens, here are some examples:

Require LTBCOIN **or** TOKENLY

``` LTBCOIN,TOKENLY ```

Require LTBCOIN **and** TOKENLY:

``` LTBCOIN_TOKENLY ```

Require LTBCOIN **and** TOKENLY... **or** STAFF

``` LTBCOIN_TOKENLY,STAFF ```

In the "Amount required for access" field, the amounts are just comma separated in same order as tokens. e.g ``` 5000,1,1 ``` for the above example which would required 5,000 LTBCOIN & 1 TOKENLY **or** just 1 STAFF token.
