### ISSUE TITLE
User post history on profiles

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/tokenly-cms#24]
This is something that was supposed to get done a while ago but sort of fell off the radar.

pretty self explanatory. Basically on user profiles you should be able to see a full history of threads, replies and blog posts that the user has posted (not sure if forum posts and blog posts should be together in the same list). These are all in seperate tables (forum_topics and forum_posts for e.g) so there might be some tricky merging needed.

It would also be nice if there was a user setting where they could hide this data from the public, but still be able to view it themselves when logged in.

**Comment by cherapple** [comment]
It is also not possible to search on an author's name in the Newsroom and bring up their published articles.

**Comment by cryptonaut420** [comment]
@cherapple are you sure? You should be able to change the newsroom filter to "Finished & Published", then type in a username into the textbox. for instance I just typed "johnbarret" and it gives me all the B&G episodes

**Comment by cherapple** [comment]
You are right! I forgot it defaults to "ready" and that I need to sort on "finished."
