### ISSUE TITLE
Contributor profile pages provide links to published works

### ISSUE THREAD

**Issue by cherapple** [tokenly/tokenly-cms#70]
Right now, once a post falls of the front page, it's difficult to find again.

**Comment by cryptonaut420** [comment]
are you not able to change the filter in the Newsroom  to "Finished & Published" and search from there?

**Comment by cherapple** [comment]
Yes, I can, but is that a community-wide function?

**Comment by cryptonaut420** [comment]
ah, yeah at the moment no its not. this ties in to issue #24 then

**Comment by cherapple** [comment]
Ah yes. I missed that. You can close this one then.
