### ISSUE TITLE
Podcast content doesn't display right on Feedburner

### ISSUE THREAD

**Issue by misterdna** [tokenly/tokenly-cms#73]
1) Smart apostrophes (curled the proper direction, rather than "dumb" internet apostrophes that are vertical) appear as "€™" in Feedburner.

2) When there's text followed by a plain URL (with a space? or return separating them), they display in Feedburner with no space or return between the text and the URL.

These issues don't appear on LTB.com, but they do in Feedburner. I've seen the issues in other LTB podcasts, not just my own.

**Comment by cryptonaut420** [comment]
I have the apostrophe thing fixed, hopefully for good this time. Not too sure about that missing space in between text and links, might be something funky going on with markdown. Also at least one case I found with that, there wasnt actually any space, just looked like there was cause the link gets pushed down to the next line on the LTB site, but not on the feedburner page. 

closing this one for now

**Comment by misterdna** [comment]
cool, thanks!

i’m sure i’ll find some other little things to bug you about soon.

:)

-r
