### ISSUE TITLE
See user's number of posts more places

### ISSUE THREAD

**Issue by misterdna** [tokenly/tokenly-cms#75]
Here are instances where I can't see the number of posts a users has made, but wish I could:
1) User's Profile
2) Forum posts when viewed on mobile site
3) Forum posts when viewed on iOS app

**Comment by cryptonaut420** [comment]
Post counts (among lots of other info) now shows up in user profiles, and I made a temporary fix to show post counts on mobile devices as well (the new design will have a better mobile version anyway)
