### ISSUE TITLE
Install failed.

### ISSUE THREAD

**Issue by y-zono** [tokenly/tokenly-cms#89]
Hi

I got this error below when I accessed to install URL. "http://MyDomain/install"

```
Fatal error: Class 'Slick_Core_Model' not found in /var/www/html/install/index.php on line 7
```

I checked /var/www/slick/autoload.php then I noticed the include path was not correct.

```
error_log($fullPath,0);
if(file_exists($fullPath)){

Error log showed $fullPath = /var/www/slick/Slick/Core/Model.php ... Correct file path is /var/www/slick/Core/Model.php.
```

I replaced to /var/www/slick/Core/Model.php but "include" return "FALSE" somehow..

Can you share any clues?

```
/var/www/conf/config.php
define('SITE_BASE', '/var/www'); //base path to installation, typically one level up from web root
define('SITE_PATH', SITE_BASE.'/html'); //web root
define('FRAMEWORK_PATH', SITE_BASE.'/slick');
```

**Comment by cryptonaut420** [comment]
@y-zono try pulling the latest version, re-import the "tokenly-clean.sql" file and try the install file again, should work now.

**Comment by y-zono** [comment]
@cryptonaut420 Thank you so much. It works!
