### ISSUE TITLE
Internal Server Error if .htaccess file is enable.

### ISSUE THREAD

**Issue by y-zono** [tokenly/tokenly-cms#90]
I just installed Tokenly CMS.

I can see the TOP page but I got 404 error when I accessed to http://MyDomain/account.

I set up .htaccess then I got Internal Server Error both http://MyDomain/ and http://MyDomain/account.

```
/var/www/html/.htaccess

Options -MultiViews
RewriteEngine on
#RewriteBase /

RewriteRule ^api/v1/(.*)$ api.php?v=1&params=$1&%{QUERY_STRING} [L]
RewriteCond %{SCRIPT_FILENAME} !api\.php$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?params=$1&%{QUERY_STRING} [L]
```

```
/etc/apache2/apache2.conf

<Directory /var/www/>
        Options Indexes FollowSymLinks
        #AllowOverride None
        AllowOverride All
        Require all granted
</Directory>
```

```
/var/www/conf/config.php

define('SITE_BASE', '/var/www'); //base path to installation, typically one level up from web root
define('SITE_PATH', SITE_BASE.'/html'); //web root
define('FRAMEWORK_PATH', SITE_BASE.'/slick');
```

How to fix it and I want to know about how to output debug message. I'm not familiar with slick framework.

Any help will be helpful.

**Comment by cryptonaut420** [comment]
Do you have the apache rewrite module enabled? ```sudo a2enmod rewrite```

**Comment by cryptonaut420** [comment]
actually, if your getting a 404.. when you went on the installation page to create your account etc., did you check off all the boxes for the different available Apps? You need at least Dashboard, Accounts and Pages enabled

**Comment by y-zono** [comment]
Fixed! What I did are here...

1. sudo a2enmod rewrite
2. sudo /etc/init.d/apache2 restart

Thank you very much. ... and I'm sorry for my poor understanding..

**Comment by cryptonaut420** [comment]
No problem!

Also you can find general php/apache errors in /var/log/apache2/error.log

**Comment by y-zono** [comment]
I checked all of the boxes when I installed. Thank you for sharing log dir.
