### ISSUE TITLE
Asset Information invisible in google chrome

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#95]
The pop-up can be seen as the button is clicked in a flash and then disappears while the screen stays dimmed as pictured, when you click to dispel the information that you can't see, the information momentarily flashes visible again as it de-activates and the screen returns to normal.

![image](https://cloud.githubusercontent.com/assets/6858319/10111605/0e508c90-638a-11e5-95a5-ad33cc9a4b36.png)

**Comment by cryptonaut420** [comment]
@AdamBLevine let me know if this still occurs for you
