### ISSUE TITLE
Forum quotes displayed on front page should have basic formatting or not include undifferentiated quoted text

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#96]
![image](https://cloud.githubusercontent.com/assets/6858319/10145127/2c36ecec-65d6-11e5-9837-020fe3e2c2bb.png)

Here's an example of the problem, the quoted text continues until "That's the best idea i've yet heard for a prediction market use-case" and it's impossible to tell that or even see that the speaker has changed the way it's currently displayed.   The simplest thing would be to not include quoted text in these clips to avoid the problem.

**Comment by cryptonaut420** [comment]
blockquoted text is no longer included

**Comment by AdamBLevine** [comment]
Looks much better now, and I like the post-title too
