### ISSUE TITLE
Allow users/subforums/reported posts/other arbitrary rules to be excluded from the front page forum feed

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#97]
![image](https://cloud.githubusercontent.com/assets/6858319/10145173/6d778888-65d6-11e5-940b-1a0ff9869c29.png)

The new system opens the door to getting premium front page exposure just by being the most recent person to have posted, which means that the until-now harmless self promotion threads suddenly have a path to the front page with a simple bump.   This is one of several reasons we need to be able to detach certain content from showing up on the front page.

**Comment by cryptonaut420** [comment]
It's currently based on your personal filters from the "Filter Boards [+]" section on Recent Posts, so maybe we just need to change what default boards are shown, and make sure they are moderated?

**Comment by David-R-Allen** [comment]
I discussed this briefly with Nick and agree that only moderated default forums are shown.

**Comment by cryptonaut420** [comment]
the default list of boards to exclude is now an app setting instead of hard coded. closing this for now
